keys:
  # Users
  - &users:
    - &marcocondrache B88BEFC2DA78218F568EA53E209101AD5F0E04C6

creation_rules:
  - path_regex: hosts/quemo/secrets.ya?ml$
    key_groups:
      - pgp:
          - *marcocondrache
  - path_regex: hosts/xawed/secrets.ya?ml$
    key_groups:
      - pgp:
          - *marcocondrache
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - pgp:
          - *marcocondrache
