keys:
  # Users
  - &users:
    - &marcocondrache 4A635CD360D1AE1E64067700CA28E81C05CBB973

creation_rules:
  - path_regex: hosts/quemo/secrets.ya?ml$
    key_groups:
    - pgp:
      - *marcocondrache
  - path_regex: hosts/xawed/secrets.ya?ml$
    key_groups:
    - pgp:
      - *marcocondrache