keys:
  # Users
  - &users:
    - &marcocondrache B88BEFC2DA78218F568EA53E209101AD5F0E04C6

  - &hosts:
    - &atlas age1fd3cpl94vd7j4wpz6260kflwtwyz79w0vvf2le6lllx8y8ele47qg77sc9
    - &athena age1gmz08ryz60hv2c0svm3flsq5h80llgspt3rutvqgy239scjq89js59zmpm

creation_rules:
  - path_regex: hosts/atlas/secrets.ya?ml$
    key_groups:
      - age:
        - *atlas
        pgp:
        - *marcocondrache

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
        - *atlas
        - *athena
        pgp:
        - *marcocondrache
